[profile.default]
version = "0.0.0"
src = "src"
out = "out"
libs = ["dependencies"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000
verbosity = 3
wrap_comments = true
gas_reports = []
show_progess = true
fs_permissions = [{ access = "read-write", path = "./.temp"}]

[fuzz]
runs = 1024

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.5.0"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARB_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
shape_sepolia = "${SHAPE_SEPOLIA_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
base = "${BASE_RPC_URL}"
shape = "${SHAPE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
arbitrum_sepolia = {  key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
base_sepolia = {  key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.basescan.org/api" }
mainnet = { key = "${ETHERSCAN_KEY}"}
arbitrum = { key = "${ETHERSCAN_KEY}", url = "https://api.arbiscan.io/api" }
base = { key = "${ETHERSCAN_KEY}", url = "https://api.basescan.org/api" }